exp: TextClassification

mode:
    - train

models: 
    hf_text_classification_model:
      - distilbert/distilbert-base-uncased

#loadPretrained: False

#samplePercent: 100

epochs: 20
batchSize: 16

numLabels: 27

id2label:
    0: Miley Cyrus
    1: Taylor Swift
    2: Demi Lovato
    3: Mariah Carey
    4: Christina Aguilera
    5: Britney Spears
    6: Aretha Franklin
    7: Etta James
    8: Nancy Sinatra
    9: Elvis Presley
    10: Chuck Berry
    11: The Beatles
    12: Green Day
    13: Pearl Jam
    14: Blink-182
    15: Coldplay
    16: Imagine Dragons
    17: Foo Fighters
    18: Johnny Cash
    19: Dolly Parton
    20: Glen Campbell
    21: Shania Twain
    22: Garth Brooks
    23: Dixie Chicks
    24: Carrie Underwood
    25: Jason Aldean
    26: Miranda Lambert

trainfpath: ./data/allLyricstrain.tsv

validfpath: ./data/allLyricsval.tsv

modelfpath: ./model/distilbert

device: cuda
